//! Cross-binary `.bvvi` interop test — closes
//! `beads_viewer_rust-api-freeze-tui-ux-p14-followups-1xz.1`.
//!
//! `fixtures/go_v0.24.1_sample.bvvi` was written by the real Go `bv` binary
//! (v0.24.1, `go install github.com/Dicklesworthstone/beads_viewer/cmd/bv@latest`),
//! not by this Rust crate. It was generated by running
//! `bv --search "authentication" --robot-search --search-mode hybrid`
//! against a 3-issue fixture repo (FIX-1/FIX-2/FIX-3 — see the doc strings
//! below for their exact title/description/labels, reproduced here so the
//! test is self-contained and doesn't need the original fixture repo on
//! disk) with `provider=hash dim=384`, which is exactly the format
//! `bv_search::index_sync::default_index_path` and
//! `bv_search::embedder::DEFAULT_DIM` already assume.
//!
//! What this proves: `VectorIndex::load` correctly parses a real Go-written
//! file (container-format interop), AND `hash_embed` over Go's
//! `IssueDocument` text layout (id×3, title×2, labels, description,
//! newline-joined — `bv_search::query::issue_document`) reproduces the
//! exact same vectors Go computed (embedding-algorithm interop). Both were
//! required — an earlier investigation pass found the container format
//! already matched, but the embedder had two real bugs (missing ASCII
//! lowercase-folding before hashing, and missing signed
//! feature-hashing — Go accumulates ±1.0 per token based on the hash's top
//! bit, this port always accumulated +1.0) that made the *contents* diverge
//! even though the *format* didn't. Both are fixed in
//! `bv_search::embedder`; this test is the permanent regression guard.
//!
//! What this does NOT prove (documented per the bead's acceptance
//! criteria item 3 — the reverse direction needs a live Go binary, which
//! cannot be invoked from a Rust test): that a `.bvvi` file *written by
//! this Rust crate* loads correctly in the Go binary. This step was not
//! automated because it requires a live Go toolchain, which is not
//! assumed to be present in CI. Manual verification steps for that
//! direction, recorded here instead of as a doc-list (clippy's
//! `doc_lazy_continuation` rejects unindented list continuations):
//!
//! Step 1 — install Go bv: `go install
//! github.com/Dicklesworthstone/beads_viewer/cmd/bv@latest`.
//!
//! Step 2 — build a small fixture repo with `.beads/issues.jsonl` (see the
//! `fixture_docs` helper below for content that matches this test).
//!
//! Step 3 — run any `bvr` command that calls
//! `bv_search::index_sync::sync_index` + `VectorIndex::save` against that
//! fixture (e.g. drive the TUI's Ctrl+S semantic search once) to produce a
//! Rust-written `.bvvi`.
//!
//! Step 4 — copy that file to `<fixture>/.bv/semantic/index-hash-384.bvvi`
//! in a directory the Go binary can see, then run `bv --search "<query>"
//! --robot-search --search-mode hybrid` there and confirm Go loads it
//! without error and returns sane results. Go's `LoadOrNewVectorIndex`
//! silently rebuilds on any load failure, so a successful load with
//! `"loaded":true` and no corrupt-file backup appearing next to the index
//! is the pass signal — an unnoticed silent-rebuild would be the actual
//! failure mode to watch for.

use bv_search::embedder::hash_embed;
use bv_search::query::issue_document;
use bv_search::vector_index::VectorIndex;

/// The exact 3-issue fixture used to generate the committed `.bvvi` file.
/// Reproduced here (not read from a fixture repo on disk) so this test has
/// no external dependency beyond the committed binary fixture.
fn fixture_docs() -> Vec<(&'static str, String)> {
    vec![
        (
            "FIX-1",
            issue_document(
                "FIX-1",
                "Fix login authentication bug",
                &["auth".to_string()],
                "Users cannot log in with valid credentials after the session refactor.",
            ),
        ),
        (
            "FIX-2",
            issue_document(
                "FIX-2",
                "Add dark mode toggle to settings",
                &["ui".to_string()],
                "Users want a dark mode option in the UI preferences panel.",
            ),
        ),
        (
            "FIX-3",
            issue_document(
                "FIX-3",
                "Refactor database connection pooling",
                &["db".to_string()],
                "Connection pool leaks under high load, needs refactor for stability.",
            ),
        ),
    ]
}

fn fixture_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/go_v0.24.1_sample.bvvi")
}

#[test]
fn go_written_index_loads_and_has_expected_shape() {
    let idx = VectorIndex::load(&fixture_path()).expect("load Go-written .bvvi");
    assert_eq!(idx.dim, 384, "Go used the default hash-embedder dim");
    assert_eq!(idx.len(), 3);
    for (id, _) in fixture_docs() {
        assert!(idx.get(id).is_some(), "missing entry {id}");
    }
}

#[test]
fn rust_hash_embed_reproduces_go_computed_vectors_exactly() {
    let idx = VectorIndex::load(&fixture_path()).expect("load Go-written .bvvi");
    for (id, doc) in fixture_docs() {
        let go_vec = &idx.get(id).expect("entry present").vector;
        let rust_vec = hash_embed(&doc, idx.dim);
        assert_eq!(go_vec.len(), rust_vec.len(), "{id}: dim mismatch");
        for (i, (g, r)) in go_vec.iter().zip(rust_vec.iter()).enumerate() {
            assert!(
                (g - r).abs() < 1e-5,
                "{id}: component {i} diverges — go={g} rust={r} (embedder algorithm mismatch)"
            );
        }
    }
}

#[test]
fn go_written_index_ranks_the_same_as_go_reported() {
    // Go's own --robot-search run over this fixture (query "authentication",
    // hybrid mode, default preset) ranked FIX-1 > FIX-2 > FIX-3 by
    // text_score (0.622 > ~0 > ~0 — FIX-2/FIX-3 don't mention
    // "authentication" at all). Confirm the Rust-recomputed cosine
    // similarity against the Go-stored vectors preserves that ordering —
    // the whole point of byte-exact embeddings is that ranking doesn't
    // silently drift between the two binaries.
    let idx = VectorIndex::load(&fixture_path()).expect("load Go-written .bvvi");
    let query_vec = hash_embed("authentication", idx.dim);
    let hits = idx
        .search_top_k(&query_vec, 3)
        .expect("search_top_k over Go-written index");
    assert_eq!(
        hits[0].issue_id, "FIX-1",
        "highest text relevance must rank first"
    );
}
