[package]
name = "bv-update"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
ureq = { version = "3", default-features = false, features = ["rustls", "gzip"] }
zip = { version = "2", default-features = false, features = ["deflate"] }
tar = { version = "0.4" }
flate2 = { version = "1" }
