[package]
name = "bv-export"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bv-core = { path = "../bv-core" }
jiff = { workspace = true }
tiny-http = { version = "0.12", package = "tiny_http" }
thiserror = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
